### ISSUE TITLE
Hash missing

### ISSUE THREAD

**Issue by TheDatadrainer** [queueRAM/ti_graph_link#1]
Hi.
I have a problem with my old TI-Graph Link as it is recognized as a TUSB3410 Boot Device. As this chip have this descriptor embedded in ROM and used it if the bootloader does not find a matching USB data or I²C ROM, and as the TUSB3410 seems to be working fine, my first suspect is the 24LC64. I desoldered it and I made a dump.
Then I compiled your source. And by comparing the two files (my bin and the ti_graph_link_silver.eep compiled from your source) I see a difference in the area 0x10002 to 0x1100E. Do you have any idea why?
Can you please put the ti_graph_link_silver.sha1 in your repo so that is it can be used to check the build validity. Thank you very much for that :) It will help confirm my dump is corrupted somehow.

What is strange is that except that area, the rest of the data is the same, which mean depending of what this area of data is doing the problem can be elsewhere in the circuit... But I don't know where, the TPS715 is okay, so are the resistors. If you have any idea, I'm taking it! Thanks for your help.

Regards

**Comment by queueRAM** [comment]
Thanks for letting me know about the missing sha1 file!

> I see a difference in the area 0x10002 to 0x1100E. Do you have any idea why?

What do you mean by these offsets? My dump is only 0x1400 bytes long. Note that I didn't dump the full EEPROM, only probed the bus during the TUSB3410's boot sequence FW transfer.

**Comment by TheDatadrainer** [comment]
Thank you for answer and for the sha1 file.
Whoops, I put an extra zero, just see that. The area with different data is at offset 0x1002 to 0x110E (8KB ROM anyway). My mistake.
Maybe I have a different version of the firmware. I have dumped the ROM several time with the same output each time.
If you want I can sent it to you. I'm not an electronics engineer but for what I understand this circuit (version B) is quite simple in its design. I have another cable but I would like to understand what happened with this one, as it can happen again. And I don't like to trash things if they can be fixed!
The 24LC64 is driven by the TUSB3410 at 400 KHz and is forced read only because WP is hardwired to VSS. So no possible writing or desync.
I checked the traces around both chips and no problem here. With or without the EEPROM, the cable is detected as a "TUSB3410 Boot Device" (ID 0x3410) with no problem (but it should be detected as a "TI-GRAPH LINK USB" (ID 0xE001) with the EEPROM in). When using TI development driver, data can be sent. That's what make me think the TUSB3410 is working fine. I checked all the resistors around and their values are correct (none burned). So if the EEPROM is working fine too where the problem can be? That's bugging me...
As you have made an extensive work on this cable, I hope you can give me clues. Thank you very very much in advance.
Kind regards.

**Comment by queueRAM** [comment]
If only the area 0x1002 to 0x110E is different, then it sounds like you have a corrupted EEPROM. There is a checksum in the header at offset 0x05 which covers the entire 0x1400 binary (0x0006-0x1405). Therefore if you have any bytes different in that range, then byte 0x05 should also differ. I suspect corrupted EEPROM and this is causing the checksum to fail and the application to not load. I've dumped the EEPROM from several different revisions of the "B" Silver Link and they have all been the same. That said, I would be interested in seeing your EEPROM dump.

If you want to see specifically what the data should look like, I annotated much of the [asm file](https://github.com/queueRAM/ti_graph_link/blob/main/ti_graph_link_silver.asm#L3031-L3050). The offsets here are relative to the application binary (so 0x0000 in the asm is 0x0006 in the EEPROM). Therefore, 0x1002 is in the `Manufacturer String` section:
```
00000ff0: 0354 0065 0078 0061 0073 0020 0049 006e  .T.e.x.a.s. .I.n
00001000: 0073 0074 0072 0075 006d 0065 006e 0074  .s.t.r.u.m.e.n.t
00001010: 0073 0024 0354 0049 002d 0047 0052 0041  .s.$.T.I.-.G.R.A
00001020: 0050 0048 0020 004c 0049 004e 004b 0020  .P.H. .L.I.N.K.
00001030: 0055 0053 0042 0041 81ff ff00 0000 00cf  .U.S.B.A........
```

**Comment by TheDatadrainer** [comment]
Did you get my emails where I explained the problem is solved by dumping your firmware?
I replied from my email client because I have joined photos, but I don't know if GitHub allow this...

**Comment by queueRAM** [comment]
No, I have not received any emails from you. I think if you reply to this GitHub notification in email it will just go to some throwaway address. You can find my email address in the git repo commits, reach out to me on Discord, or PM me on [Cemetech](https://www.cemetech.net/forum/profile.php?mode=viewprofile&u=34762)
